name: Generate Local Krew Manifest

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., v1.0.0)'
        required: true
        type: string

jobs:
  publish-krew:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: Checkout kubectl-safe repository
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
    
    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.25'
    
    - name: Determine version
      id: version
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
        elif [ "${{ github.event_name }}" = "repository_dispatch" ]; then
          echo "version=${{ github.event.client_payload.version }}" >> $GITHUB_OUTPUT
        else
          echo "version=${{ github.ref_name }}" >> $GITHUB_OUTPUT
        fi
        echo "Version: $(cat $GITHUB_OUTPUT)"
    
    - name: Build and package release assets
      run: make build-all

    - name: Calculate checksums
      id: checksums
      run: |
        LINUX_AMD64_CHECKSUM=$(sha256sum dist/kubectl-safe-linux-amd64.tar.gz | awk '{print $1}')
        LINUX_ARM64_CHECKSUM=$(sha256sum dist/kubectl-safe-linux-arm64.tar.gz | awk '{print $1}')
        DARWIN_AMD64_CHECKSUM=$(sha256sum dist/kubectl-safe-darwin-amd64.tar.gz | awk '{print $1}')
        DARWIN_ARM64_CHECKSUM=$(sha256sum dist/kubectl-safe-darwin-arm64.tar.gz | awk '{print $1}')
        WINDOWS_AMD64_CHECKSUM=$(sha256sum dist/kubectl-safe-windows-amd64.tar.gz | awk '{print $1}')
        echo "LINUX_AMD64_CHECKSUM=$LINUX_AMD64_CHECKSUM" >> $GITHUB_ENV
        echo "LINUX_ARM64_CHECKSUM=$LINUX_ARM64_CHECKSUM" >> $GITHUB_ENV
        echo "DARWIN_AMD64_CHECKSUM=$DARWIN_AMD64_CHECKSUM" >> $GITHUB_ENV
        echo "DARWIN_ARM64_CHECKSUM=$DARWIN_ARM64_CHECKSUM" >> $GITHUB_ENV
        echo "WINDOWS_AMD64_CHECKSUM=$WINDOWS_AMD64_CHECKSUM" >> $GITHUB_ENV

    - name: Write Krew plugin manifest locally
      run: |
        VERSION="${{ steps.version.outputs.version }}"
        mkdir -p plugins
        cat <<EOF > plugins/safe.yaml
apiVersion: krew.googlecode.com/v1alpha2
kind: Plugin
metadata:
  name: safe
spec:
  version: ${VERSION}
  homepage: https://github.com/bjrooney/kubectl-safe
  shortDescription: Interactive safety net for dangerous kubectl commands
  description: |
    kubectl-safe provides an interactive safety net for dangerous kubectl commands.
    
    It acts as a wrapper around destructive kubectl operations to prevent common
    mistakes by:
    - Requiring explicit --context and --namespace flags for dangerous commands
    - Showing interactive confirmation prompts with target details
    - Acting as a final checkpoint before potentially destructive operations
    
    Dangerous commands include: delete, apply, create, replace, patch, edit, 
    scale, rollout, drain, cordon, uncordon, and taint.
    
    For safe commands like get, describe, logs, etc., this plugin acts as a
    transparent pass-through to kubectl without any safety checks.
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/bjrooney/kubectl-safe/releases/download/${VERSION}/kubectl-safe-linux-amd64.tar.gz
    sha256: "${LINUX_AMD64_CHECKSUM}"
    bin: kubectl-safe
  - selector:
      matchLabels:
        os: linux
        arch: arm64
    uri: https://github.com/bjrooney/kubectl-safe/releases/download/${VERSION}/kubectl-safe-linux-arm64.tar.gz
    sha256: "${LINUX_ARM64_CHECKSUM}"
    bin: kubectl-safe
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/bjrooney/kubectl-safe/releases/download/${VERSION}/kubectl-safe-darwin-amd64.tar.gz
    sha256: "${DARWIN_AMD64_CHECKSUM}"
    bin: kubectl-safe
  - selector:
      matchLabels:
        os: darwin
        arch: arm64
    uri: https://github.com/bjrooney/kubectl-safe/releases/download/${VERSION}/kubectl-safe-darwin-arm64.tar.gz
    sha256: "${DARWIN_ARM64_CHECKSUM}"
    bin: kubectl-safe
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/bjrooney/kubectl-safe/releases/download/${VERSION}/kubectl-safe-windows-amd64.tar.gz
    sha256: "${WINDOWS_AMD64_CHECKSUM}"
    bin: kubectl-safe.exe
EOF